name: Check CLA

on:
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - reopened
      - opened
      - closed
      - synchronize

jobs:
  check-cla:
    if: >-
      !github.event.repository.fork
      && (
        github.event.comment.body == '@conda-bot check'
        || github.event_name == 'pull_request'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Check CLA
        uses: conda/actions/check-cla@check-cla
        with:
          # [required]
          # label to add when actor has signed the CLA
          label: cla-signed
          # [required]
          # the GitHub Personal Access Token to comment and label with
          token: ${{ github.token }}
